config/routes.rb
Rails.application.routes.draw do
  get 'welcomes/index'

  post 'users/create'
  get 'users/login'
  get 'users/register'
  get 'users/index'

  get 'users/verify'            => 'welcomes#index'
  get 'users/verify/:id'        => 'users#verify#:id'
  get 'users/verify/:id/:token' => 'users#activate#:id#:token'

  get 'users/activate'            => 'welcomes#index'
  get 'users/activate/:id'        => 'welcomes#index'
  get 'users/activate/:id/:token' => 'users#activate#:id#:token'
  
  post 'users/activate'

  namespace :main, path: ':master_url' do
    root 'sites#index'
    get  'sites/login'
    post 'sites/attemp_login'
    namespace :dashboard do
      root 'index#index'
      get 'index/index'
      
      # get 'web_managers/announcement'
      # get 'web_managers/primary'
      # get 'web_managers/others'
      resources :masters
    end
    get '/:action' => 'sites#:action'
  end

  root 'welcomes#index'
end

app/models/master.rb
class Master < ActiveRecord::Base
	has_one :site
	has_and_belongs_to_many :administrators, :join_table => "administrators", :class_name => "User"
	has_and_belongs_to_many :authors, :join_table => "authors", :class_name => "User"
end

app/controllers/main/dashboard/dashboards_controller.rb
class Main::Dashboard::DashboardsController < ApplicationController
layout 'dashboard'
  def index
      Rails.logger.info "WELCOME TO DASHBOARD"
  end
end

app/controllers/main/dashboard/index_controller.rb
class Main::Dashboard::IndexController < ApplicationController
layout 'dashboard'
before_action :init_master, only: [:index]
before_action :check_user_privileges
respond_to :html, :js

def index

end


end

app/controllers/main/dashboard/masters_controller.rb
class Main::Dashboard::MastersController < ApplicationController
before_action :all_masters, only: [:index, :create, :update, :destroy]
before_action :set_master, only: [:edit, :update, :destroy, :show]
before_action :init_master
layout 'main'

respond_to :html, :js

def new
  @master = Master.new
end
def create
  @master = Master.create(conf_params)
end

def update
  @master.update_attributes(conf_params)
end

def destroy
  @master.destroy
end

private
  def all_masters
    @masters = Master.all
  end
  def set_master
    @master = Master.find(params[:id])
  end
  def conf_params
    params.require(:master).permit(:title,:url)
  end
end

app/controllers/main/dashboard/web_managers_controller.rb
class Main::Dashboard::WebManagersController < ApplicationController
  respond_to :html, :js
  layout 'main'
  def announcement
  end

  def primary
  end

  def others
  end
end

app/helpers/dashboard/masters_helper.rb
module Dashboard::MastersHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/main/dashboard/index_helper.rb
module Main::Dashboard::IndexHelper
end

app/helpers/main/dashboard/web_managers_helper.rb
module Main::Dashboard::WebManagersHelper
end

app/views/backup_view/main/dashboard/masters/_form_master.html.erb
<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title"><i class="fa fa-pencil fa-fw"></i>Add/Edit Conference</h3>
    </div>
    <div class="panel-body">
    <%= controller.action_name == 'new' ? action='create' : action='show' %>
    <%= simple_form_for @master,url: {action: action}, remote: true do |f| %>
      <%= f.input :url, label: 'URL' %>
      <%= f.input :title, label: 'Title' %>
      <%= f.button :submit %>
    <% end %>
    </div>
</div>


app/views/backup_view/main/dashboard/masters/_form_master_edit.html.erb
<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title"><i class="fa fa-pencil fa-fw"></i>Add/Edit Conference</h3>
    </div>
    <div class="panel-body">
	    <%= simple_form_for [master,url:=], remote: true do |f| %>
				<%= f.input :url, label: 'URL' %>
				<%= f.input :title, label: 'Title' %>
				<%= f.button :submit %>
			<% end %>
    </div>
</div>


app/views/backup_view/main/dashboard/masters/_index.html.erb
<!-- Page Heading -->
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">
            Master Conference <small>
            <%= link_to new_main_dashboard_master_path, remote: true do %>
                <button class="btn btn-default">Create New</button>
            <% end %>
        </small>
        </h1>
    </div>
</div>

<div class="row">
    <div class="col-lg-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><i class="fa fa-list fa-fw"></i> All Conference</h3>
            </div>
            <div class="panel-body">
                <table class="table table-bordered" id="master-list"></table>
            </div>
        </div>
    </div>
    <div class="col-lg-6" >
        <div id="form-master" style:"display:none;"></div>
    </div>
    
</div>
<!-- /.row -->

app/views/backup_view/main/dashboard/masters/_master.html.erb
<tr>
  <td><%= master.id %></td>
  <td><%= master.title %></td>
  <td><%= master.url%></td>
  <td>
    <center>
    <%= link_to :controller=>"masters",:action =>"edit",:id => master, remote: true do %>
      <button class="btn btn-primary btn-xs">Edit</button>
    <% end %>
    <%= link_to main_dashboard_master_path(@master_url.url, master), remote: true, method: :delete, data: {confirm:  'Are you sure?'} do %>
      <button class="btn btn-danger btn-xs">Delete</button>
    <% end %>
    </center>
  </td>
</tr>

app/views/backup_view/main/dashboard/masters/create.js.erb
$('#master-list').html("<%= j (render @masters) %>");
$('#form-master').hide();

app/views/backup_view/main/dashboard/masters/destroy.js.erb
$('#master-list').html("<%= j (render @masters) %>");

app/views/backup_view/main/dashboard/masters/edit.js.erb
$('#form-master').html("<%= j (render 'form_master', :master => @master) %>");
$('#form-master').show();

app/views/backup_view/main/dashboard/masters/index.js.erb
$('#content').html("<%= j (render 'index') %>");
$('#master-list').html("<%= j (render @masters) %>");

app/views/backup_view/main/dashboard/masters/new.js.erb
$('#form-master').html("<%= j (render 'form_master', :master => @master) %>");
$('#form-master').show();

app/views/backup_view/main/dashboard/masters/update.js.erb
$('#master-list').html("<%= j (render @masters) %>");
$('#form-master').hide();