config/routes.rb
Rails.application.routes.draw do
  get 'welcomes/index'

  post 'users/create'
  get 'users/login'
  get 'users/register'
  get 'users/index'

  get 'users/verify'            => 'welcomes#index'
  get 'users/verify/:id'        => 'users#verify#:id'
  get 'users/verify/:id/:token' => 'users#activate#:id#:token'

  get 'users/activate'            => 'welcomes#index'
  get 'users/activate/:id'        => 'welcomes#index'
  get 'users/activate/:id/:token' => 'users#activate#:id#:token'
  
  post 'users/activate'

  namespace :main, path: ':master_url' do
    root 'sites#index'
    get  'sites/login'
    post 'sites/attemp_login'
    namespace :dashboard do
      root 'index#index'
      get 'index/index'
      
      # get 'web_managers/announcement'
      # get 'web_managers/primary'
      # get 'web_managers/others'
      resources :masters
    end
    get '/:action' => 'sites#:action'
  end

  root 'welcomes#index'
end

app/models/administrator.rb
class Administrator < ActiveRecord::Base
	
end

app/models/master.rb
class Master < ActiveRecord::Base
	has_one :site
	has_and_belongs_to_many :administrators, :join_table => "administrators", :class_name => "User"
	has_and_belongs_to_many :authors, :join_table => "authors", :class_name => "User"
end

app/models/site.rb
class Site < ActiveRecord::Base
	belongs_to :master
end

app/models/user.rb
class User < ActiveRecord::Base
  #belongs_to :administrator
  
  has_and_belongs_to_many :conferences_admined, :join_table => "administrators", :class_name =>"Master"
  has_and_belongs_to_many :conferences_authored, :join_table => "authors", :class_name => "Master"  
end

app/models/user_register.rb
class UserRegister < ActiveRecord::Base
  validates :email, :presence => true
  validates :first_name, :presence => true
  validates :last_name, :presence => true

  validates :password, :presence => true,
                       :length => {:minimum => 6}, 
                        confirmation: true
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper ApplicationHelper

  def not_found
    raise ActionController::RoutingError.new('Not Found')
  end

  def get_master_all
    @masters = Master.all
  end

  def init_master
    _temp       = params[:master_url];
    @master_url = Master.find_by_url(_temp)
    
    if !@master_url.present?
      flash[:danger] = "Conference ' #{_temp} ' not found."
      redirect_to(root_path)   
    else
      return true
    end
  end

  def check_user_privileges 
    if !is_user_authorized?
      redirect_to main_sites_login_path
    end
  end

  private 
  def is_user_authorized? 
    thisConferenceId = @master_url.id 
    thisUser         = nil

    if session[:userId].present? 
      thisUser       = User.find_by_id(session[:userId])
      isUserAuthored = thisUser.conferences_authored_ids.include? thisConferenceId
    else
      flash[:notice] = "Please login first"
      return false
    end 
    
    if isUserAuthored
      return true
    else
      flash[:notice] = "Sufficient Rights"
      return false
    end
  end
end

app/controllers/main/access_controller.rb
class Main::AccessController < ApplicationController
  before_action :init_master
  def index
   
  end
end

app/controllers/main/sites_controller.rb
class Main::SitesController < ApplicationController
  before_action :init_master
  
  def index
  end

  def schedule
  end

  def pricing
  end

  def contact
  end
  
  def login
  end

  def logout
    _temp = 1
    reset_session
    Rails.logger.info(_temp); 
    flash[:notice] = "Successfuly, Logout"
    redirect_to(:action => "login")  
  end

  def attemp_login
   if is_login_success?
     redirect_to(main_dashboard_root_path)
   else
     redirect_to(:action => 'login')
   end
  end

  private

  def is_login_success? 
    if params[:email].present? && params[:password].present?
      found_user = User.find_by_email(params[:email])
    else
      flash[:error] = "Please fill out all credentials needed"
      return false
    end

    if found_user != nil
      authorized_user = found_user.authenticate(params[:password])
    else
      flash[:error] = "User not found"
      return false
    end

    if authorized_user 
      session[:userId] = found_user.id
      return true
    else
      flash[:error] = "Wrong Username / Password"
      return false
    end

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout 'user'

  def index
  end

  def register
    @register = UserRegister.new
  end

  def login 
  end 

  def verify
    if !User.exists?(:id => params[:id])
      @id    = params[:id]
      @token = params[:token]
    else
      flash[:danger] = "Your account already validated"
      redirect_to(root_path)
    end
  end

  def activate
    if params[:id].present? && params[:token].present? 
      id    = params[:id]
      token = params[:token]

      userNew = UserRegister.find(id)
      user    = nil 

      if User.exists?(:id => id) 
        flash[:danger] = "Your account already validated"
      elsif userNew.token == token 
        user = User.new(
              :id              => userNew.id,
              :email           => userNew.email,
              :password_digest => userNew.password_digest,
              :first_name      => userNew.first_name,
              :organization    => userNew.organization,
              :country         => userNew.country
             )

        if user.save
          flash[:success] = "Your account was activated, please login to access conferences"
        else
          flash[:danger] = "Something error occurred while we creating your account."
        end
      else
        flash[:danger] = "Incorrect Token, please check your email"
      end 
    end

    redirect_to(root_path);
  end

  def create
    @register = UserRegister.new(register_params) 

    if @register.valid? 
      @register.token = SecureRandom.urlsafe_base64(16);
      @register.save  
      url = request.host + ':' + request.port.to_s

      RegistrationMailer.email_token(@register, url).deliver_now

      flash[:success] = "Thank you for your registration. Please check your email for validating account."
      redirect_to(root_path)
    else
      flash[:danger] = "Error occured while registering your account"
      render('users/register')
    end   
  end

  private
    def register_params 
      params.require(:user_register).permit(:first_name, :last_name, 
                                   :email, :country, :organization, 
                                   :password, :password_confirmation, :sender
                                  )
    end 

end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
  layout 'welcome'

  before_action :get_master_all

  def index
  end

  def register
    @register = User.new
    @sender   = 'welcome'
  end

  def login
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard/masters_helper.rb
module Dashboard::MastersHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/main/access_helper.rb
module Main::AccessHelper
end

app/helpers/main/dashboard/index_helper.rb
module Main::Dashboard::IndexHelper
end

app/helpers/main/dashboard/web_managers_helper.rb
module Main::Dashboard::WebManagersHelper
end

app/helpers/main/sites_helper.rb
module Main::SitesHelper
end

app/helpers/mein/deshbord/mester_helper.rb
module Mein::Deshbord::MesterHelper
end

app/helpers/mein/index_helper.rb
module Mein::IndexHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/welcomes/_form_register.html.erb
<%= simple_form_for @register, url: {action: 'create'} do |f| %>
  <div class="form-group">
    <legend><span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span> Register</legend>
  </div>
  <div class="form-group">
    <div class="col-md-6">
      <%= f.input :first_name, label: 'First Name', class: "form-control", placeholder: "First Name is Required"  %>
    </div>
    <div class="col-md-6">
      <%= f.input :last_name, label: 'Last Name', class: "form-control", placeholder: "Last Name is Required"   %>
    </div>
  </div>
  <div class="form-group">
    <%= f.input :email, label: 'E-mail', class: "form-control", placeholder: "Email is Required" %>
  </div>
  <div class="form-group">
    <%= f.input :country, priority: ["Indonesia"] %>
  </div>
  <div class="form-group">
    <%= f.input :organization, label: 'Organization', class: "form-control", placeholder: "Your Current Workplace Name. Leave blank if private." %>
  </div>
  <div class="form-group">
    <%= f.input :password, label: 'Password', class: "form-control", placeholder: "Please input 6 characters or more" %>
  </div>
  <div class="form-group">
    <%= f.input :password_confirmation, label: 'Re-Type Password', class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.button :submit, class: "btn btn-primary", :onclick => "return confirm('Are you sure form data is correct?')" %>
  </div>
  <div class="form-group">
    <small>Already have an account ?</small>&nbsp;
    <%= link_to "Login Now", welcomes_login_path, class: "btn btn-xs btn-primary" %>
  </div>
<% end %>

app/views/welcomes/index.html.erb
<div class="row">
  <div class="col-md-6">
    <%= link_to "Login", users_login_path, class: "btn btn-primary btn-lg btn-block" %>
  </div>
  <div class="col-md-6">
    <%= link_to "Register", users_register_path, class: "btn btn-success btn-lg btn-block" %>
  </div>
</div>
<div class="row">
</div>

app/views/welcomes/register.html.erb
<%= render "users/form_register" %>