config/routes.rb
Rails.application.routes.draw do
  get 'welcomes/index'

  post 'users/create'
  get 'users/login'
  get 'users/register'
  get 'users/index'

  get 'users/verify'            => 'welcomes#index'
  get 'users/verify/:id'        => 'users#verify#:id'
  get 'users/verify/:id/:token' => 'users#activate#:id#:token'

  get 'users/activate'            => 'welcomes#index'
  get 'users/activate/:id'        => 'welcomes#index'
  get 'users/activate/:id/:token' => 'users#activate#:id#:token'
  
  post 'users/activate'

  namespace :main, path: ':master_url' do
    root 'sites#index'
    get  'sites/login'
    post 'sites/attemp_login'
    namespace :dashboard do
      root 'index#index'
      get 'index/index'
      
      # get 'web_managers/announcement'
      # get 'web_managers/primary'
      # get 'web_managers/others'
      resources :masters
    end
    get '/:action' => 'sites#:action'
  end

  root 'welcomes#index'
end

app/models/administrator.rb
class Administrator < ActiveRecord::Base
	
end

app/models/master.rb
class Master < ActiveRecord::Base
	has_one :site
	has_and_belongs_to_many :administrators, :join_table => "administrators", :class_name => "User"
	has_and_belongs_to_many :authors, :join_table => "authors", :class_name => "User"
end

app/models/site.rb
class Site < ActiveRecord::Base
	belongs_to :master
end

app/models/user.rb
class User < ActiveRecord::Base
  #belongs_to :administrator
  
  has_and_belongs_to_many :conferences_admined, :join_table => "administrators", :class_name =>"Master"
  has_and_belongs_to_many :conferences_authored, :join_table => "authors", :class_name => "Master"  
end

app/models/user_register.rb
class UserRegister < ActiveRecord::Base
  validates :email, :presence => true
  validates :first_name, :presence => true
  validates :last_name, :presence => true

  validates :password, :presence => true,
                       :length => {:minimum => 6}, 
                        confirmation: true
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper ApplicationHelper

  def not_found
    raise ActionController::RoutingError.new('Not Found')
  end

  def get_master_all
    @masters = Master.all
  end

  def init_master
    _temp       = params[:master_url];
    @master_url = Master.find_by_url(_temp)
    
    if !@master_url.present?
      flash[:danger] = "Conference ' #{_temp} ' not found."
      redirect_to(root_path)   
    else
      return true
    end
  end

  def check_user_privileges 
    if !is_user_authorized?
      redirect_to main_sites_login_path
    end
  end

  private 
  def is_user_authorized? 
    thisConferenceId = @master_url.id 
    thisUser         = nil

    if session[:userId].present? 
      thisUser       = User.find_by_id(session[:userId])
      isUserAuthored = thisUser.conferences_authored_ids.include? thisConferenceId
    else
      flash[:notice] = "Please login first"
      return false
    end 
    
    if isUserAuthored
      return true
    else
      flash[:notice] = "Sufficient Rights"
      return false
    end
  end
end

app/controllers/main/access_controller.rb
class Main::AccessController < ApplicationController
  before_action :init_master
  def index
   
  end
end

app/controllers/main/sites_controller.rb
class Main::SitesController < ApplicationController
  before_action :init_master
  
  def index
  end

  def schedule
  end

  def pricing
  end

  def contact
  end
  
  def login
  end

  def logout
    _temp = 1
    reset_session
    Rails.logger.info(_temp); 
    flash[:notice] = "Successfuly, Logout"
    redirect_to(:action => "login")  
  end

  def attemp_login
   if is_login_success?
     redirect_to(main_dashboard_root_path)
   else
     redirect_to(:action => 'login')
   end
  end

  private

  def is_login_success? 
    if params[:email].present? && params[:password].present?
      found_user = User.find_by_email(params[:email])
    else
      flash[:error] = "Please fill out all credentials needed"
      return false
    end

    if found_user != nil
      authorized_user = found_user.authenticate(params[:password])
    else
      flash[:error] = "User not found"
      return false
    end

    if authorized_user 
      session[:userId] = found_user.id
      return true
    else
      flash[:error] = "Wrong Username / Password"
      return false
    end

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout 'user'

  def index
  end

  def register
    @register = UserRegister.new
  end

  def login 
  end 

  def verify
    if !User.exists?(:id => params[:id])
      @id    = params[:id]
      @token = params[:token]
    else
      flash[:danger] = "Your account already validated"
      redirect_to(root_path)
    end
  end

  def activate
    if params[:id].present? && params[:token].present? 
      id    = params[:id]
      token = params[:token]

      userNew = UserRegister.find(id)
      user    = nil 

      if User.exists?(:id => id) 
        flash[:danger] = "Your account already validated"
      elsif userNew.token == token 
        user = User.new(
              :id              => userNew.id,
              :email           => userNew.email,
              :password_digest => userNew.password_digest,
              :first_name      => userNew.first_name,
              :organization    => userNew.organization,
              :country         => userNew.country
             )

        if user.save
          flash[:success] = "Your account was activated, please login to access conferences"
        else
          flash[:danger] = "Something error occurred while we creating your account."
        end
      else
        flash[:danger] = "Incorrect Token, please check your email"
      end 
    end

    redirect_to(root_path);
  end

  def create
    @register = UserRegister.new(register_params) 

    if @register.valid? 
      @register.token = SecureRandom.urlsafe_base64(16);
      @register.save  
      url = request.host + ':' + request.port.to_s

      RegistrationMailer.email_token(@register, url).deliver_now

      flash[:success] = "Thank you for your registration. Please check your email for validating account."
      redirect_to(root_path)
    else
      flash[:danger] = "Error occured while registering your account"
      render('users/register')
    end   
  end

  private
    def register_params 
      params.require(:user_register).permit(:first_name, :last_name, 
                                   :email, :country, :organization, 
                                   :password, :password_confirmation, :sender
                                  )
    end 

end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
  layout 'welcome'

  before_action :get_master_all

  def index
  end

  def register
    @register = User.new
    @sender   = 'welcome'
  end

  def login
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard/masters_helper.rb
module Dashboard::MastersHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/main/access_helper.rb
module Main::AccessHelper
end

app/helpers/main/dashboard/index_helper.rb
module Main::Dashboard::IndexHelper
end

app/helpers/main/sites_helper.rb
module Main::SitesHelper
end

app/helpers/mein/index_helper.rb
module Mein::IndexHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/backup_view/layouts/_footer.html.erb
<footer>
  <div class="row">
    <% # Line  %>
    <h2 class="page-header"></h2>
    <div class="col-lg-12"></div>
    <p>Copyright &copy; Your Website 2014</p>
  </div>
</footer>

app/views/backup_view/layouts/_navbar.html.erb
<!-- Navigation
-->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display
    -->
    <div class="navbar-header">
      <button class="navbar-toggle" data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" type="button">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">
        <i class="fa fa-fw fa-university"></i>
        SIMK 
      </a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to("Login", :action=>'login') %>
        </li>
        <li>
          <%= link_to("Schedule", :action=>'schedule') %>
        </li>
        <li>
          <%= link_to("Pricing", :action=>'pricing') %>
        </li>
        <li>
          <%= link_to("Maps & Contact", :action=>'contact') %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/backup_view/layouts/_navmain.html.erb
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="index.html"><i class="fa fa-fw fa-university"></i>SIMK</a>
            </div>
            <!-- Top Menu Items -->
            <ul class="nav navbar-right top-nav">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> John Smith <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="#"><i class="fa fa-fw fa-user"></i> Profile</a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-fw fa-power-off"></i> Log Out</a>
                        </li>
                    </ul>
                </li>
            </ul>

app/views/backup_view/layouts/_sidebar.html.erb
 <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav side-nav">
                    <li>
                        <%= link_to main_dashboard_root_path, remote: true do %>
                            <i class="fa fa-fw fa-dashboard"></i> Dashboard
                        <% end %>
                    </li>
                    <li>
                        <%= link_to main_dashboard_masters_path, remote: true do %>
                            <i class="fa fa-fw fa-globe"></i> Master Conference
                        <% end %>
                    </li>
                     <li>
                        <a href="javascript:;" data-toggle="collapse" data-target="#demo"><i class="fa fa-fw fa-book"></i> Site Manager <i class="fa fa-fw fa-caret-down"></i></a>
                        <ul id="demo" class="collapse">
                            <li>
                                <%= link_to 'Announcement',main_dashboard_web_managers_announcement_path, remote: true %>
                            </li>
                            <li>
                                <%= link_to 'Primary Info',main_dashboard_web_managers_primary_path, remote: true%>
                            </li>
                            <li>
                                <%= link_to 'Other Info',main_dashboard_web_managers_others_path, remote: true %>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>

app/views/backup_view/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html></html>
<head>
  <title><%= if @master_url.present? ? @master_url.title %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
</head>
<body>
  <%= yield %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>

app/views/backup_view/layouts/main.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html></html>
<head>
  <title><%#= @master_url.title %> | Dashboard </title>
  <%= stylesheet_link_tag    'main', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="wrapper">
	<!-- Navigation -->
	<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
		<%= render(:partial=>'layouts/navmain') %>
		<%= render(:partial=>'layouts/sidebar') %>
	</nav>
   	<div id="page-wrapper">
    	<div class="container-fluid">
			<div id="content"><%= yield %></div>
		</div>
		<span class="empty_fill"></span>
	</div>
</div>	
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>

app/views/layouts/_footer.html.erb
<footer>
  <div class="row">
    <% # Line  %>
    <h2 class="page-header"></h2>
    <div class="col-lg-12"></div>
    <p>Copyright &copy; Your Website 2014</p>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<!-- Navigation
-->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display
    -->
    <div class="navbar-header">
      <button class="navbar-toggle" data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" type="button">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">
        <i class="fa fa-fw fa-university"></i>
        SIMK 
      </a>
    </div>
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to("Login", :action=>'login') %>
        </li>
        <li>
          <%= link_to("Schedule", :action=>'schedule') %>
        </li>
        <li>
          <%= link_to("Pricing", :action=>'pricing') %>
        </li>
        <li>
          <%= link_to("Maps & Contact", :action=>'contact') %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navmain.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">SIMK</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <!-- <ul class="nav navbar-nav">
        
      </ul> -->
      <% if (session[:administrator].present?) %> 
      <ul class="nav navbar-nav navbar-right">
        <div class="btn-group">
          <a href="#" class="btn btn-default">Admin 1 - Author</a>
          <a href="#" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Profile</a></li>
            <li><a href="#">Logout</a></li>
          </ul>
        </div>
      </ul>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/_sidebar.html.erb
<div class="col-lg-3">
    <div id="menu">
        <div class="panel list-group">
         <a href="#" class="list-group-item"><b>VIEW PROCEEDINGS</b></a>
         <a href="#" class="list-group-item" data-toggle="collapse" data-target="#program" data-parent="#menu"><b>PROGRAMS</b></a>
         <div id="program" class="sublinks collapse">
          <a class="list-group-item small" href="#">At A Glance</a>
          <a class="list-group-item small" href="#">Full Programs</a>
         </div>

          <a href="#" class="list-group-item" data-toggle="collapse" data-target="#author" data-parent="#menu"><b>AUTHOR MENU</b></a>
         <div id="author" class="sublinks collapse">
           <a class="list-group-item small" href="#">Submissions</a>
           <a class="list-group-item small" href="#">Files</a>
         </div>
        </div>          
    </div>  
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
  <head>
    <title><%= @master_url.present? ? @master_url.title : nil %></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render(:partial=>'layouts/navmain') %>
    <div id="content">
      <%= yield %>
    </div>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </body>
</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
  <title><%= @master_url.title %>&nbsp;<%= @currentPage %> </title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render(:partial=>'layouts/navmain') %>
<div class="container-fluid">
<div class="row">
<%= render(:partial=>'layouts/sidebar') %>
  <div class="col-md-9">
    <div class="panel panel-default" style="min-height:600px;">
      <div class="panel-heading"><b>Papers Proceedings</b></div>
        <div class="row content" id="content" style="padding-left:10px;padding-top:20px;">
          <%= yield %>
        </div>
      </div>
    </div>
  </div>
</div>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>

app/views/layouts/user.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
  <head>
    <title><%= @master_url.present? ? @master_url.title : nil %></title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
  <div class="container" style="padding-top:20px;">
    <div class="row">
      <div class="col-md-5">
        <div class="panel panel-default">
          <div class="panel-body"> 
            <div class="left-panel-content" id="left-panel-content">
              <%= yield %>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-7">
        <div class="row">
          <%= render "welcomes/alert" %>
        </div>
        <div class="row">
          <div class="list-group">
            <% if @register.present? && @register.errors.messages != nil %>
              <h4 class="list-group-item-heading">Lorem Ipsum</h4>
              <p class="list-group-item-text">Donec id elit non mi porta gravida at eget metus. Maecenas sed diam eget risus varius blandit.</p>
            <% end %>
          </div>
       </div>
      </div>
    </div>
  </div>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </body>
</html>

app/views/layouts/welcome.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
  <head>
    <title><%= @master_url.present? ? @master_url.title : nil %></title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
  <div class="container" style="padding-top:20px;">
    <div class="row">
      <div class="col-md-5">
        <div class="panel panel-default">
          <div class="panel-body"> 
            <div class="left-panel-content" id="left-panel-content">
              <%= yield %>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-7">
        <div class="row">
          <%= render "welcomes/alert" %>
        </div>
        <div class="row">
          <div class="list-group">
            <% @masters.each do |master| %>
              <%= link_to({action: "index",master_url: master.url, controller: "main/sites"}, class: "list-group-item") do %>
                <h4 class="list-group-item-heading"><%= master.title %></h4>
                <p class="list-group-item-text">Donec id elit non mi porta gravida at eget metus. Maecenas sed diam eget risus varius blandit.</p>
              <% end %>
           <% end %>
           </div>
       </div>
      </div>
    </div>
  </div>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </body>
</html>